SYSTEM:
    DEVICE: "gpu"

PATHS:
    RESULT_DIR:
        PATH: 'E:\Albert_BigFile\Data\260618_SkNeXt_dataset\result'

TASK:
    CHANNELS: ["F", "C", "P", "S.soma", "S.spine", "S.bouton"]
    CHANNELS_EXTRA_OPTS: [{"P":{"type": "skeleton", "dilation": 1}}]
    CHANNEL_WEIGHTS: [1, 1, 1, 1, 1, 1]
    WATERSHED:
        SEED_CHANNELS: ["C", "P"]
        SEED_CHANNELS_THRESH: ["auto", "auto"]
        TOPOGRAPHIC_SURFACE_CHANNEL: "F"
        GROWTH_MASK_CHANNELS: ["F"]
        GROWTH_MASK_CHANNELS_THRESH: [0.1]

DATA:
    PATCH_SIZE: [32, 128, 128, 1]
    NORMALIZATION:
        PERC_CLIP:
            ENABLE: True
            LOWER_PERC: 0.1
            UPPER_PERC: 99.8
        TYPE: "zero_mean_unit_variance"
    TRAIN:
        PATH: 'E:\Albert_BigFile\Data\260618_SkNeXt_dataset\train\raw'
        GT_PATH: 'E:\Albert_BigFile\Data\260618_SkNeXt_dataset\train\label'
    VAL:
        PATH: 'E:\Albert_BigFile\Data\260618_SkNeXt_dataset\val\raw'
        GT_PATH: 'E:\Albert_BigFile\Data\260618_SkNeXt_dataset\val\label'
    INFER:
        PATH: 'E:\Albert_BigFile\Data\260611_SkNeXt_test\tif_test\infer'
        GT_PATH: 'E:\Albert_BigFile\Data\260611_SkNeXt_test\tif_test\infer\label'
        CHANNEL: [0]
        CHANNEL_NAME: 'result0'
        SKELETON_PATH: 'E:\Albert_BigFile\Data\260611_SkNeXt_test\tif_test\infer'

AUGMENTOR:
    ENABLE: True
    RANDOM_ROT: True
    ZOOM: True
    ZOOM_RANGE: [0.7, 1.3]
    VFLIP: True
    HFLIP: True
    ZFLIP: True
    BRIGHTNESS: True
    CONTRAST: True
    AFFINE_MODE: "reflect"

MODEL:
    LOAD_CHECKPOINT: True
    FEATURE_MAPS: [32, 64, 128, 256, 320]

TRAIN:
    ENABLE: True
    OPTIMIZER: "ADAMW"
    LR: 1.E-4
    BATCH_SIZE: 2
    EPOCHS: 500
    PATIENCE: 100
    LR_SCHEDULER:
        NAME: "warmupcosine"
        MIN_LR: 1.E-6
        WARMUP_COSINE_DECAY_EPOCHS: 5

INFER:
    ENABLE: False
    POST_PROCESSING:
        ENABLE: True
        OPERATIONS: ["fill_holes", "remove_small"]
        VALUES: [None, 100]
