"""Desktop smoke check; run explicitly on a machine with a display."""
import sys
from pathlib import Path
import tkinter as tk
import subprocess
import tempfile
import time
from unittest.mock import patch

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from sknext.gui import Application


root = tk.Tk()
root.withdraw()
try:
    with patch.object(Application, "refresh_gpus"):
        app = Application(root)
    root.update_idletasks()
    app.workflow.set("Inference")
    app.run_id.set("12")
    app.variables["TRAIN.LR"].set("0.001")
    cfg, run_id = app.collect()
    assert cfg.INFER.ENABLE and not cfg.TRAIN.ENABLE
    assert cfg.TRAIN.LR == 0.001 and run_id == 12
    assert len(app.variables) > 80
    app.events.put(("gpus", {"Test GPU": "GPU-test"}))
    app.poll()
    assert app.gpu.get() == "Test GPU"
    app.append_log("Smoke test log\n")
    assert "Smoke test log" in app.log.get("1.0", "end")
    real_popen = subprocess.Popen
    with tempfile.TemporaryDirectory() as folder:
        app.workdir.set(folder)
        app.workflow.set("Training")
        for name in ("raw", "label"):
            (Path(folder) / name).mkdir()
        def worker(command, **kwargs):
            """Launch a harmless output-only child after checking the workflow command.

            Args:
                command: Command generated by the GUI launcher.
                **kwargs: Popen options forwarded to the replacement child.

            Returns:
                The real subprocess handle used to exercise log and completion handling.
            """
            assert kwargs["env"]["CUDA_VISIBLE_DEVICES"] == "GPU-test"
            assert command[1:4] == ["-u", "-m", "sknext"]
            return real_popen([sys.executable, "-u", "-c", "print('worker smoke output')"], **kwargs)
        with patch("sknext.gui.subprocess.Popen", side_effect=worker):
            app.start()
        deadline = time.monotonic() + 10
        while app.process is not None and time.monotonic() < deadline:
            root.update()
            time.sleep(0.01)
        assert app.process is None
        assert app.status.get() == "Completed"
        assert "worker smoke output" in app.log.get("1.0", "end")
        assert list(Path(folder).rglob("gui-*.yaml"))
        logs = list(Path(folder).rglob("gui-*.log"))
        assert "worker smoke output" in logs[0].read_text()
    print(f"GUI smoke passed: {len(app.variables)} fields, workflow, GPU selection, worker, snapshots and logs.")
finally:
    root.destroy()
